apiVersion: v1
kind: Secret
metadata:
  name: postgres-db-secret
type: Opaque
stringData:
  password: "pass"

---

apiVersion: v1
kind: Secret
metadata:
  name: mongo-db-secret
type: Opaque
stringData:
  password: "pass"

---

apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
type: Opaque
stringData:
  secret: "8N1G8WR0DCVY5ZSYONASE2MKlTXYSQ5UWQCS1K3K6WYUAH4OQN7Dlf9SWVSNWCTYBLLCJRNBXQPSQMA90RTSM46"